export const RESTAURANT_FOOD_LIST_REQUEST = "RESTAURANT_FOOD_LIST_REQUEST"
export const RESTAURANT_FOOD_LIST_SUCCESS = "RESTAURANT_FOOD_LIST_SUCCESS"
export const RESTAURANT_FOOD_LIST_FAIL = "RESTAURANT_FOOD_LIST_FAIL"
