export const RESTAURANT_FOOD_LIST_REQUEST = "RESTAURANT_FOOD_LIST_REQUEST"
export const RESTAURANT_FOOD_LIST_SUCCESS = "RESTAURANT_FOOD_LIST_SUCCESS"
export const RESTAURANT_FOOD_LIST_FAIL = "RESTAURANT_FOOD_LIST_FAIL"

export const FOOD_DETAILS_REQUEST = "FOOD_DETAILS_REQUEST"
export const FOOD_DETAILS_SUCCESS = "FOOD_DETAILS_SUCCESS"
export const FOOD_DETAILS_FAIL = "FOOD_DETAILS_FAIL"
