export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL"

export const ORDER_DETAIL_REQUEST = "ORDER_DETAIL_REQUEST"
export const ORDER_DETAIL_SUCCESS = "ORDER_DETAIL_SUCCESS"
export const ORDER_DETAIL_FAIL = "ORDER_DETAIL_FAIL"

export const USER_ORDERS_REQUEST = "USER_ORDERS_REQUEST"
export const USER_ORDERS_SUCCESS = "USER_ORDERS_SUCCESS"
export const USER_ORDERS_FAIL = "USER_ORDERS_FAIL"
